### ISSUE TITLE
Investigate warnings when generating tear sheets

### ISSUE THREAD

**Issue by gusgordon** [quantopian/pyfolio#125]
These warnings come up when generating the full tear sheet (not sure which sheet specifically):

```
/usr/local/lib/python2.7/dist-packages/pyfolio/utils.py:140: UserWarning: Could not update cache /usr/local/lib/python2.7/dist-packages/pyfolio/data/factors.csv.Exception: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pyfolio/data/factors.csv'
  UserWarning)
/usr/local/lib/python2.7/dist-packages/matplotlib/cbook.py:133: MatplotlibDeprecationWarning: The "loc" positional argument to legend is deprecated. Please use the "loc" keyword instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
```

And these come up when generating the Bayesian sheet:

```
/usr/local/lib/python2.7/dist-packages/theano/gof/cmodule.py:297: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  rval = __import__(module_name, {}, {}, [module_name])
/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py:475: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
```

They don't seem to be affecting behavior at this point, though, and some of them (e.g. the theano one) may be due to things we can't fix within pyfolio.

**Comment by ssanderson** [comment]
The first warning is telling you that you're trying to write into pyfolio's cached factors and failing to do so because you don't have appropriate permissions on that file.  Wherever you're seeing that warning, you've got pyfolio installed in the system python, which is probably a bad idea.

The theano warning is indicating that the version of theano you're using was compiled against numpy headers from a version older than the version of numpy you're actually running against.  This isn't **necessarily** broken, but it could be, and the failure mode will be random unexplainable crashes or worse.  The right fix is to uninstall and reinstall theano, compiling against the appropriate numpy.

The matplotlib warnings look like you're calling functions with arguments that it expects to be passed by name rather than position.

**Comment by jmccorriston** [comment]
Got another reported instance of this in helpscout (https://secure.helpscout.net/conversation/145719827/8104/?folderId=605902):
"Hello I get the follwing error message in research for create_full_tear_sheet on the backtest portfolio shown at the end of the mail. Do i need to install any thing local to be able to run the tear_sheets? regards Jan /usr/local/lib/python2.7/dist-packages/pyfolio/utils.py:149: UserWarning: Could not update cache /usr/local/lib/python2.7/dist-packages/pyfolio/data/factors.csv.Exception: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pyfolio/data/factors.csv' UserWarning) KeyError Traceback (most recent call last) <ipython-input-1-c9fc6a8f0f9d> in <module>() 1 bt = get_backtest('5661aa8194997e116a3afbb0') ----> 2 bt.create_full_tear_sheet()"

I've seen this before too.

**Comment by twiecki** [comment]
@jmccorriston See https://github.com/quantopian/pyfolio/issues/129
