### ISSUE TITLE
use qgrid or some other scrollable table to display full list of positions

### ISSUE THREAD

**Issue by Jstauth** [quantopian/pyfolio#14]
with the full list of holdings from all time is a large list (>10 or so) it doesn't show up nicely in the tearsheet.

**Comment by twiecki** [comment]
Started over here: https://github.com/quantopian/pyfolio/tree/qgrid

**Comment by georgh0021** [comment]
We now have a round trip tear sheet, which should (hopefully) invalidate the need for a list of all positions for all time... Using round trips is a more nuanced way of analyzing the algo's performance, since it takes into account how often the algo rebalances, etc., and the round trip tear sheet gives much more detailed analysis that a straight-up printing of the positions (e.g. returns stats, profitability by name, etc.)

I do like the idea of using qgrid though! There just doesn't seem to be much need for it in the full tear sheet as it is right now... I'm going to close this issue.
