### ISSUE TITLE
Fama-French data is never read from cache

### ISSUE THREAD

**Issue by furmaniak** [quantopian/pyfolio#209]
In `utils.load_portfolio_risk_factors` there is a call to `get_returns_cached(filepath, get_fama_french, end)`.
However, the FamaFrench data only goes up to Sept 30, so if `end>"Sept 30"`, then the check `returns.index[-1] < latest_dt` in `utils.get_returns_cached` returns false, and the data is downloaded anew.  In tests, this is the most time-consuming part of generating a tear sheet.

**Comment by twiecki** [comment]
@furmaniak Thanks for the report, you're correct. The issue is that the Fama-French are updated but only infrequently. I'm not sure how we could know when it was updated or rather, what the latest available dt is what's on the website.

One idea would be to check the timestamp of the cache as well, rather than the latest available dt.

**Comment by twiecki** [comment]
Closed with #241.
