### ISSUE TITLE
Investigate tz issue on research

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#215]
https://www.quantopian.com/posts/help-using-pyfolio-with-zipline-in-a-notebook

**Comment by humdings** [comment]
Were those errors being thrown in the research env, or on somebody's local machine? It doesn't look like the code in the traceback matches the latest version of pyfolio.

I don't think that error will be an issue if pyfolio is updated. The following line is what was causing the error in utils.extract_rets_pos_txn_from_zipline()
`--> 369     transactions.index = transactions.index.normalize().tz_localize('utc') `

This has since been changed to 
```
if transactions.index.tzinfo is None:
        transactions.index = transactions.index.tz_localize('utc')
```

**Comment by twiecki** [comment]
Thanks @humdings. That's what I thought. I assumed `pyfolio` was updated on research but it seems that hasn't happened yet explaining the error.

**Comment by twiecki** [comment]
That indeed seems to have been the case.
