### ISSUE TITLE
Add win/loss analysis

### ISSUE THREAD

**Issue by gusgordon** [quantopian/pyfolio#24]
Might be useful to have a breakdown of win/loss percentage

**Comment by justinlent** [comment]
@twiecki I just flagged this one as 'high priority' since I think it is related to a lot of our recent discussions about computing batting averages of strategies, as well as how to define a trading decisions, etc., which I think is something fairly high on our list.  If you think this particular issue is different, feel free to re-prioritize

**Comment by twiecki** [comment]
Definitely. Still need to solve the non-0-crossing case but once we do my code should be pretty easy to add here.

**Comment by gusgordon** [comment]
This would take commission costs into account, right? e.g. if I buy at $1, sell at $2, but it cost me $2 for the transaction I would have a net loss of $1 and this would be a "loss". I'm pretty sure we take transaction costs into account for everything in pyfolio but just clarifying.

**Comment by twiecki** [comment]
https://github.com/quantopian/pyfolio/pull/210
