### ISSUE TITLE
Fama-French plot should not throw exception if backtest returns start earlier than Fama-French factors

### ISSUE THREAD

**Issue by justinlent** [quantopian/pyfolio#303]
the proper behavior should be something like, only start the rolling Fama-French factors from the time which the backtest returns indexes AND the Fama-French indexes intersect

![image](https://cloud.githubusercontent.com/assets/6541022/15449599/e7cd4f54-1f36-11e6-8ee6-b5daaeda0384.png)

**Comment by georgh0021** [comment]
It appears that the Fama French factors go back to at least the beginning of 1950. Backtests that long would surely encounter numerous problems all over pyfolio: data source issues, extremely long compute times, difficult-to-read graphs, etc.

The main use case of pyfolio is not to give basic analysis for long periods of time, but to provide detailed analysis of a relatively short period of time (say, 2-5 years): as such, there isn't much support for long backtests. I'll close this issue now, as the fix to this problem is slightly out of scope.
