### ISSUE TITLE
Fama-French should use multivariate regression

### ISSUE THREAD

**Issue by twiecki** [quantopian/pyfolio#379]
https://github.com/quantopian/pyfolio/blob/master/pyfolio/timeseries.py#L563 shows we are using separate linear regressions which is problematic because the factors are confounded. 

We should instead use multivariate regression: http://stackoverflow.com/questions/19991445/run-an-ols-regression-with-pandas-data-frame

CC @jlowin

**Comment by georgh0021** [comment]
This is a pretty serious bug. We need to get this fixed ASAP, especially given the work that is in the pipeline from #400 (i.e. the four-factor "post-Fama-French" alpha).

**Comment by jlowin** [comment]
Indeed -- this could dramatically affect the attribution numbers that @georgh0021 is working on

**Comment by georgh0021** [comment]
It turns out that this is not as easy as I originally thought. We don't want a multivariate regression, we want a _rolling_ multivariate regression. Pandas used to support this sort of thing with 'pd.stats.ols.MovingOLS', but that has unfortunately been deprecated.

A solution is [described on StackOverflow](https://stackoverflow.com/questions/37317727/deprecated-rolling-window-option-in-ols-from-pandas-to-statsmodels), which seems to be the easiest way to deal with this. I'll open a PR for this now.
