### ISSUE TITLE
Importing pyfolio implicitly imports every module in PyFolio

### ISSUE THREAD

**Issue by ssanderson** [quantopian/pyfolio#73]
This has two major negative consequences:

1. During development, an import-time error (e.g. a syntax error, or a missing package) *anywhere* in the repo causes all imports to fail.
2. Importing anything in the library takes an annoyingly long (almost 3 seconds on my machine) amount of time.  Most of this time is spent in `seaborn.__init__`.

@twiecki is there a reason we're doing this in the module `__init__`?

```
from . import utils
from . import timeseries
from . import pos
from . import txn

from .tears import *  # noqa
from .plotting import *  # noqa
```

**Comment by twiecki** [comment]
I'm not a big fan of having the user know about sub and subsubmodules for using the module. If you look e.g. at `pandas` or `seaborn`, most of the user-facing functions are in the main name-space. The reason for the #noqa is that `flake8` complains otherwise. We should probably add the functions we want to expose via `__all__` however.

**Comment by ssanderson** [comment]
> If you look e.g. at pandas or seaborn, most of the user-facing functions are in the main name-space.

This is my least favorite thing about the pydata ecosystem.  It makes it a pain to find where things are actually defined, which often contributes to circular dependencies which get resolved with runtime imports rather than proper package structure (which in turn bites us on Quantopian because we run in a chroot for security reasons), and it means that performance issues in **any** of your dependencies leak into module in your code, which creates an unpleasant user experience.

I'm not arguing that there's no place for putting important functionality in a top-level namespace, but we should be careful about what we choose to export in this way, and we should be aware of the performance and maintenance costs that come from this.

**Comment by twiecki** [comment]
I don't think it's a big deal. People can always selectively import if they want to and there's no sense in importing a module if you don't want to use it.

**Comment by ssanderson** [comment]
> People can always selectively import if they want to and there's no sense in importing a module if you don't want to use it.

What's meant here by "people can always selectively import"?  The issue here, in my mind, is precisely the fact that people **can't** selectively import, because if you import from **any** file in PyFolio you trigger execution of **every** file in PyFolio.  This means that, as an application developer, I can't import PyFolio at module scope anywhere in my application if three seconds of startup latency is unacceptable (which it is in Quantopian Research).  This in turn means that if I want to use PyFolio I have to do lazy runtime imports everywhere, which hurts package organization and makes module dependencies unclear.

There are real arguments to be made that namespace convenience is worth the cost of the above issues, but I don't think it's fair to say this isn't an issue.

**Comment by twiecki** [comment]
Ah, you're right. I had assumed a selective import gets around that issue.

**Comment by twiecki** [comment]
I think we should raise an issue with seaborn about this.

**Comment by ssanderson** [comment]
The root cause of the slowness is in matplotlib.font_manager:

```
In [1]: %prun -r -s cumtime -l 20 import matplotlib.pyplot

ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.002    0.002    2.461    2.461 <string>:1(<module>)
        1    0.001    0.001    2.413    2.413 pyplot.py:17(<module>)
        1    0.001    0.001    2.392    2.392 colorbar.py:20(<module>)
        1    0.001    0.001    2.380    2.380 collections.py:10(<module>)
        1    0.002    0.002    2.374    2.374 backend_bases.py:28(<module>)
        1    0.001    0.001    2.365    2.365 textpath.py:3(<module>)
        1    0.001    0.001    2.362    2.362 font_manager.py:21(<module>)
        1    0.000    0.000    2.361    2.361 font_manager.py:952(pickle_load)
        1    0.003    0.003    2.361    2.361 {cPickle.load}
        1    0.001    0.001    2.358    2.358 font_manager.py:1013(__init__)
        2    0.098    0.049    2.275    1.137 font_manager.py:544(createFontList)
      215    0.000    0.000    2.149    0.010 afm.py:341(__init__)
      215    0.001    0.000    2.148    0.010 afm.py:323(parse_afm)
      215    0.001    0.000    1.443    0.007 afm.py:292(_parse_optional)
      182    0.979    0.005    1.434    0.008 afm.py:220(_parse_kern_pairs)
      215    0.374    0.002    0.690    0.003 afm.py:180(_parse_char_metrics)
  1298020    0.229    0.000    0.229    0.000 {method 'split' of 'str' objects}
   839978    0.157    0.000    0.157    0.000 {method 'readline' of 'file' objects}
   114276    0.087    0.000    0.107    0.000 afm.py:72(_to_list_of_floats)
   843180    0.092    0.000    0.092    0.000 {method 'startswith' of 'str' objects}
        4    0.000    0.000    0.082    0.021 font_manager.py:294(findSystemFonts)
```

https://github.com/matplotlib/matplotlib/issues/4756.

**Comment by twiecki** [comment]
OK, lets wait for upstream to fix it then. I don't think this should have any consequence for research anyhow, aren't we importing matplotlib.pyplot there by default? That way the pyfolio import should be snappy.

**Comment by jehillparikh** [comment]
Hi Guys I think I am facing an import error, both Ubuntu 14.04LTS and OSX. Using anaconda, and zipline 0.7.0 at the moment (waiting for the conda update). I am aiming to start testing pyfolio in standalone mode, when there errors are depending if I have imported pandas or not, please see below. Would appreciate if have any help here. 

import pyfolio as pf
​
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-76e20f75c9bd> in <module>()
----> 1 import pyfolio as pf

//anaconda/lib/python2.7/site-packages/pyfolio/__init__.py in <module>()
      2 
      3 from . import utils
----> 4 from . import timeseries
      5 from . import pos
      6 from . import txn

//anaconda/lib/python2.7/site-packages/pyfolio/timeseries.py in <module>()
     22 import scipy as sp
     23 import scipy.stats as stats
---> 24 from sklearn import preprocessing
     25 
     26 import statsmodels.api as sm

//anaconda/lib/python2.7/site-packages/sklearn/__init__.py in <module>()
     55 else:
     56     from . import __check_build
---> 57     from .base import clone
     58     __check_build  # avoid flakes unused variable error
     59 

//anaconda/lib/python2.7/site-packages/sklearn/base.py in <module>()
      9 from scipy import sparse
     10 from .externals import six
---> 11 from .utils.fixes import signature
     12 
     13 

//anaconda/lib/python2.7/site-packages/sklearn/utils/__init__.py in <module>()
      8 import warnings
      9 
---> 10 from .murmurhash import murmurhash3_32
     11 from .validation import (as_float_array,
     12                          assert_all_finite,

numpy.pxd in init sklearn.utils.murmurhash (sklearn/utils/murmurhash.c:5029)()

ValueError: numpy.dtype has the wrong size, try recompiling

In [2]:

d
import pandas as pd
In [3]:

 as pf
import pyfolio as pf
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-76e20f75c9bd> in <module>()
----> 1 import pyfolio as pf

//anaconda/lib/python2.7/site-packages/pyfolio/__init__.py in <module>()
      1 import warnings
      2 
----> 3 from . import utils
      4 from . import timeseries
      5 from . import pos

ImportError: cannot import name utils

**Comment by twiecki** [comment]
I think this is unrelated to pyfolio but suggests that you're using an incompatible numpy. I'd try reinstalling that and making sure you're using the anaconda python.

**Comment by jehillparikh** [comment]
Thanks for the prompt reply, I did try reinstalling it a couple of time no luck! Actually, I think zipline install using conda, downgrades the issue numpy!! The reason, I am using that is I am facing issues with pip install on zipline, which bit frustrating, and was wating for conda 0.8.14 release! Seems like I have no choice, I will give it a go! thanks for the feedback!

**Comment by jehillparikh** [comment]
Just a feedback, the issue was related to downgrading grading of numpy etc while installing zipline using conda, I can't get pip install zipline (0.8.3) to work (if you could help that would be great, I have posted details)

So end of the day, pyfolio works fine in standalone mode, and in zipline (0.7.0) installed using conda, would be good to have them working togther. Not sure if waiting for zipline conda package to 0.8.
3  is the best way forward ? I seems to have spend a lot of time installing!! 

Again many thanks for your help in first place :)

**Comment by twiecki** [comment]
Yes, I'd wait for zipline 0.8.4 on conda. I hope we can make it numpy 1.10 compatible or it might not help with this.

**Comment by jehillparikh** [comment]
Thanks that great, actually, pyfolio on conda would also be perfect Actually, I think these are main barriers to wider usage of the amazing work at quantopain. Have a look at the blogs probably installation issues, end up taking a lot of your time as well!!   

Down grading numpy to 1.9 also broke my other packages, which are even trickier to install :(((((((

**Comment by twiecki** [comment]
Yep, I'm well aware.

We can add pyfolio conda packages, just haven't so far as it should be very easy with pip install just because it doesn't require compilation but might as well add it.

**Comment by twiecki** [comment]
@jehillparikh I uploaded a conda  package. Can you try: `conda install -c quantopian pyfolio`?

**Comment by jehillparikh** [comment]
conda pyfolio works! However, numpy was upgraded during installation, to
1.10, along with others, thus zipline doen'st work anymore, which I
expected.  I got the following error whiling running your Markovitz
portfolio example.

Is it possible to build pyfolio with same version as zipline ? Otherwise we
wait till zipline upgrade ?? Thanks!


runfile('/home/jehill/temp.py', wdir='/home/jehill')
[[  2.77880107e-09]
 [  3.20322848e-06]
 [  1.54301198e-06]
 [  9.99995251e-01]]
IBM
GLD
XOM
AAPL
MSFT
TLT
SHY/home/jehill/anaconda2/lib/python2.7/site-packages/pandas/io/data.py:33:
FutureWarning:
The pandas.io.data module is moved to a separate package
(pandas-datareader) and will be removed from pandas in a future version.
After installing the pandas-datareader package (
https://github.com/pydata/pandas-datareader), you can change the import
``from pandas.io import data, wb`` to ``from pandas_datareader import data,
wb``.
  FutureWarning)
[2016-01-06 15:42] WARNING: Loader: No benchmark data found for date range.
start_date=2016-01-06 00:00:00+00:00, end_date=2016-01-06 15:42:51.878100,
url=
http://ichart.finance.yahoo.com/table.csv?s=%5EGSPC&a=0&b=6&c=2016&d=0&e=6&f=2016&g=d

/home/jehill/anaconda2/lib/python2.7/site-packages/zipline/data/loader.py:230:
FutureWarning: iterkv is deprecated and will be removed in a future
release, use ``iteritems`` instead.
  for tr_dt, curve in treasury_curves.T.iterkv():
Traceback (most recent call last):

  File "<ipython-input-1-5f378aa46f5d>", line 1, in <module>
    runfile('/home/jehill/temp.py', wdir='/home/jehill')

  File
"/home/jehill/anaconda2/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py",
line 699, in runfile
    execfile(filename, namespace)

  File
"/home/jehill/anaconda2/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py",
line 81, in execfile
    builtins.execfile(filename, *where)

  File "/home/jehill/temp.py", line 341, in <module>
    results = algo.run(data)

  File
"/home/jehill/anaconda2/lib/python2.7/site-packages/zipline/algorithm.py",
line 398, in run
    self.sim_params.first_open)

  File
"/home/jehill/anaconda2/lib/python2.7/site-packages/zipline/history/history_container.py",
line 171, in __init__
    self.create_return_frames(initial_dt)

  File
"/home/jehill/anaconda2/lib/python2.7/site-packages/zipline/history/history_container.py",
line 264, in create_return_frames
    index = pd.to_datetime(index_at_dt(history_spec, algo_dt))

  File
"/home/jehill/anaconda2/lib/python2.7/site-packages/pandas/util/decorators.py",
line 89, in wrapper
    return func(*args, **kwargs)

  File
"/home/jehill/anaconda2/lib/python2.7/site-packages/pandas/tseries/tools.py",
line 276, in to_datetime
    unit=unit, infer_datetime_format=infer_datetime_format)

  File
"/home/jehill/anaconda2/lib/python2.7/site-packages/pandas/tseries/tools.py",
line 395, in _to_datetime
    return _convert_listlike(arg, box, format)

  File
"/home/jehill/anaconda2/lib/python2.7/site-packages/pandas/tseries/tools.py",
line 383, in _convert_listlike
    raise e

ValueError: Tz-aware datetime.datetime cannot be converted to datetime64
unless utc=True


Jehill

**Comment by twiecki** [comment]
@jehillparikh Thanks for letting me know. Yeah, the only sensible thing is to have zipline work with numpy 1.10. @richafrank is working on the conda zipline package.
